name: Retag Docker Manifest
inputs:
  src:
    description: Source image name
    required: true
  dest:
    description: Destination image name
    required: true
runs:
  using: 'node12'
  main: '../lib/retag/retag.js'
