name: Deploy via GitOps

inputs:
  environment:
    description: One of production, staging, test

  new_tag:
    description: Tag name to deploy

  app:
    description: Name of app to deploy in the GitOps directory

  description:
    description: Description of this deploy

  github_auth_token:
    description: GitHub PAT that has repository_dispatch access to the GitOps repo

runs:
  using: 'node12'
  main: '../lib/deploy/deploy.js'
