on: [push, pull_request]

name: Test Actions

jobs:
  setup_protoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ./setup-protoc
        with:
          version: '3.9.1'

      - name: Check version
        run: |
          protoc --version | grep -E 3.9.1
  dxt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ./dxt
        with:
          tag: scratchimage,scratchimage2
          platforms: linux/arm64,linux/amd64,linux/arm/v7
          context: './hack/fixtures/dxt'
          dockerfile: './hack/fixtures/dxt/Dockerfile'

      - name: Check version
        run: |
          buildx version | grep -E 0.3.0
